/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmGlavna.java
 *
 * Created on Apr 25, 2012, 7:16:59 PM
 */
package forme;

import kontrolerKI.forme.GlavnaKI;
import paneli.automobili.BrisanjeAutomobilaPanel;
import paneli.dugovanja.PlacanjeDugovanjaPanel;
import paneli.automobili.PrikazAutomobilaPanel;
import paneli.automobili.PromenaAutomobilaPanel;
import paneli.automobili.UnosAutomobilaPanel;
import paneli.dugovanja.UnosDugovanjaPanel;
import paneli.intervencije.BrisanjeIntervencijaPanel;
import paneli.intervencije.PrikazIntervencijaPanel;
import paneli.intervencije.PromenaIntervencijePanel;
import paneli.intervencije.UnosIntervencijePanel;
import splashscreen.SplashScreen;

/**
 *
 * @author Rus
 */
public class FrmGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FrmGlavna
     */
    public FrmGlavna() {
        initComponents();
        GlavnaKI.vratiObjekat().postaviSveKomponente(this, jMenuBar1, jmAutomobili, jmDugovanja, jmIntervencije, jmIzlogujSe, jmiBrisanjeAutomobila, jmiBrisanjeIntervencije, jmiIzlogujSe, jmiNaplataDugovanja, jmiPrikazSvihAutomobila, jmiPrikazSvihIntervencija, jmiPromenaPodatakaAutomobila, jmiPromenaPodatakaIntervencije, jmiUnosAutomobila, jmiUnosDugovanja, jmiUnosIntervencije);
        GlavnaKI.vratiObjekat().izgledForme();
        GlavnaKI.vratiObjekat().pripremiGlavnu();
        GlavnaKI.vratiObjekat().precice();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmIntervencije = new javax.swing.JMenu();
        jmiUnosIntervencije = new javax.swing.JMenuItem();
        jmiPrikazSvihIntervencija = new javax.swing.JMenuItem();
        jmiPromenaPodatakaIntervencije = new javax.swing.JMenuItem();
        jmiBrisanjeIntervencije = new javax.swing.JMenuItem();
        jmAutomobili = new javax.swing.JMenu();
        jmiUnosAutomobila = new javax.swing.JMenuItem();
        jmiPrikazSvihAutomobila = new javax.swing.JMenuItem();
        jmiPromenaPodatakaAutomobila = new javax.swing.JMenuItem();
        jmiBrisanjeAutomobila = new javax.swing.JMenuItem();
        jmDugovanja = new javax.swing.JMenu();
        jmiUnosDugovanja = new javax.swing.JMenuItem();
        jmiNaplataDugovanja = new javax.swing.JMenuItem();
        jmIzlogujSe = new javax.swing.JMenu();
        jmiIzlogujSe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jmIntervencije.setText("Intervencije");

        jmiUnosIntervencije.setText("Unos nove intervencije");
        jmiUnosIntervencije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosIntervencijeActionPerformed(evt);
            }
        });
        jmIntervencije.add(jmiUnosIntervencije);

        jmiPrikazSvihIntervencija.setText("Prikaz svih intervencija");
        jmiPrikazSvihIntervencija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazSvihIntervencijaActionPerformed(evt);
            }
        });
        jmIntervencije.add(jmiPrikazSvihIntervencija);

        jmiPromenaPodatakaIntervencije.setText("Promena podataka intervencije");
        jmiPromenaPodatakaIntervencije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPromenaPodatakaIntervencijeActionPerformed(evt);
            }
        });
        jmIntervencije.add(jmiPromenaPodatakaIntervencije);

        jmiBrisanjeIntervencije.setText("Brisanje intervencije");
        jmiBrisanjeIntervencije.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBrisanjeIntervencijeActionPerformed(evt);
            }
        });
        jmIntervencije.add(jmiBrisanjeIntervencije);

        jMenuBar1.add(jmIntervencije);

        jmAutomobili.setText("Automobili");

        jmiUnosAutomobila.setText("Unos novog automobila");
        jmiUnosAutomobila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosAutomobilaActionPerformed(evt);
            }
        });
        jmAutomobili.add(jmiUnosAutomobila);

        jmiPrikazSvihAutomobila.setText("Prikaz svih automobila");
        jmiPrikazSvihAutomobila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazSvihAutomobilaActionPerformed(evt);
            }
        });
        jmAutomobili.add(jmiPrikazSvihAutomobila);

        jmiPromenaPodatakaAutomobila.setText("Promena podataka automobila");
        jmiPromenaPodatakaAutomobila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPromenaPodatakaAutomobilaActionPerformed(evt);
            }
        });
        jmAutomobili.add(jmiPromenaPodatakaAutomobila);

        jmiBrisanjeAutomobila.setText("Brisanje automobila");
        jmiBrisanjeAutomobila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiBrisanjeAutomobilaActionPerformed(evt);
            }
        });
        jmAutomobili.add(jmiBrisanjeAutomobila);

        jMenuBar1.add(jmAutomobili);

        jmDugovanja.setText("Dugovanja");

        jmiUnosDugovanja.setText("Unos dugovanja");
        jmiUnosDugovanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosDugovanjaActionPerformed(evt);
            }
        });
        jmDugovanja.add(jmiUnosDugovanja);

        jmiNaplataDugovanja.setText("Naplata dugovanja");
        jmiNaplataDugovanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNaplataDugovanjaActionPerformed(evt);
            }
        });
        jmDugovanja.add(jmiNaplataDugovanja);

        jMenuBar1.add(jmDugovanja);

        jmIzlogujSe.setText("Logovanje");

        jmiIzlogujSe.setText("Izloguj se");
        jmiIzlogujSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiIzlogujSeActionPerformed(evt);
            }
        });
        jmIzlogujSe.add(jmiIzlogujSe);

        jMenuBar1.add(jmIzlogujSe);

        setJMenuBar(jMenuBar1);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-800)/2, (screenSize.height-600)/2, 800, 600);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiUnosIntervencijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosIntervencijeActionPerformed

        GlavnaKI.vratiObjekat().postaviAktivanPanel(new UnosIntervencijePanel());

    }//GEN-LAST:event_jmiUnosIntervencijeActionPerformed

    private void jmiPrikazSvihIntervencijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazSvihIntervencijaActionPerformed
        // TODO add your handling code here:

        GlavnaKI.vratiObjekat().postaviAktivanPanel(new PrikazIntervencijaPanel());

    }//GEN-LAST:event_jmiPrikazSvihIntervencijaActionPerformed

    private void jmiPromenaPodatakaIntervencijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPromenaPodatakaIntervencijeActionPerformed
        // TODO add your handling code here:

        GlavnaKI.vratiObjekat().postaviAktivanPanel(new PromenaIntervencijePanel());

    }//GEN-LAST:event_jmiPromenaPodatakaIntervencijeActionPerformed

    private void jmiBrisanjeIntervencijeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBrisanjeIntervencijeActionPerformed
        // TODO add your handling code here:

        GlavnaKI.vratiObjekat().postaviAktivanPanel(new BrisanjeIntervencijaPanel());

    }//GEN-LAST:event_jmiBrisanjeIntervencijeActionPerformed

    private void jmiUnosAutomobilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosAutomobilaActionPerformed
        // TODO add your handling code here:

        GlavnaKI.vratiObjekat().postaviAktivanPanel(new UnosAutomobilaPanel());

    }//GEN-LAST:event_jmiUnosAutomobilaActionPerformed

    private void jmiPrikazSvihAutomobilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazSvihAutomobilaActionPerformed
        // TODO add your handling code here:

        GlavnaKI.vratiObjekat().postaviAktivanPanel(new PrikazAutomobilaPanel());

    }//GEN-LAST:event_jmiPrikazSvihAutomobilaActionPerformed

    private void jmiPromenaPodatakaAutomobilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPromenaPodatakaAutomobilaActionPerformed
        // TODO add your handling code here:

        GlavnaKI.vratiObjekat().postaviAktivanPanel(new PromenaAutomobilaPanel());

    }//GEN-LAST:event_jmiPromenaPodatakaAutomobilaActionPerformed

    private void jmiBrisanjeAutomobilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiBrisanjeAutomobilaActionPerformed
        // TODO add your handling code here:

        GlavnaKI.vratiObjekat().postaviAktivanPanel(new BrisanjeAutomobilaPanel());

    }//GEN-LAST:event_jmiBrisanjeAutomobilaActionPerformed

    private void jmiUnosDugovanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosDugovanjaActionPerformed
        // TODO add your handling code here:

        GlavnaKI.vratiObjekat().postaviAktivanPanel(new UnosDugovanjaPanel());

    }//GEN-LAST:event_jmiUnosDugovanjaActionPerformed

    private void jmiNaplataDugovanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNaplataDugovanjaActionPerformed
        // TODO add your handling code here:

        GlavnaKI.vratiObjekat().postaviAktivanPanel(new PlacanjeDugovanjaPanel());

    }//GEN-LAST:event_jmiNaplataDugovanjaActionPerformed

    private void jmiIzlogujSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiIzlogujSeActionPerformed

        GlavnaKI.vratiObjekat().izlogujSe();

    }//GEN-LAST:event_jmiIzlogujSeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGlavna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            SplashScreen ss = new SplashScreen(3000);

            @Override
            public void run() {
                new FrmGlavna().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAutomobili;
    private javax.swing.JMenu jmDugovanja;
    private javax.swing.JMenu jmIntervencije;
    private javax.swing.JMenu jmIzlogujSe;
    private javax.swing.JMenuItem jmiBrisanjeAutomobila;
    private javax.swing.JMenuItem jmiBrisanjeIntervencije;
    private javax.swing.JMenuItem jmiIzlogujSe;
    private javax.swing.JMenuItem jmiNaplataDugovanja;
    private javax.swing.JMenuItem jmiPrikazSvihAutomobila;
    private javax.swing.JMenuItem jmiPrikazSvihIntervencija;
    private javax.swing.JMenuItem jmiPromenaPodatakaAutomobila;
    private javax.swing.JMenuItem jmiPromenaPodatakaIntervencije;
    private javax.swing.JMenuItem jmiUnosAutomobila;
    private javax.swing.JMenuItem jmiUnosDugovanja;
    private javax.swing.JMenuItem jmiUnosIntervencije;
    // End of variables declaration//GEN-END:variables
}
