/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BrisanjeAutomobilaPanel.java
 *
 * Created on Apr 26, 2012, 1:06:08 AM
 */
package paneli.automobili;

import java.awt.Color;
import javax.swing.BorderFactory;
import kontrolerKI.automobili.BrisanjeAutomobilaKI;

/**
 *
 * @author Rus
 */
public class BrisanjeAutomobilaPanel extends javax.swing.JPanel {

    /**
     * Creates new form BrisanjeAutomobilaPanel
     */
    public BrisanjeAutomobilaPanel() {
        initComponents();
        BrisanjeAutomobilaKI.vratiObjekat().postaviSveKomponente(this, jlObavestenja, jmiDetaljiAutomobila, jmiObrisiAutomobil, jpmObrisiAutomobil, jrbJmbgVlasnika, jrbRegistracija, jtblPromenaAutomobila, jtfPretraga);
        BrisanjeAutomobilaKI.vratiObjekat().srediPopUpMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmObrisiAutomobil = new javax.swing.JPopupMenu();
        jmiDetaljiAutomobila = new javax.swing.JMenuItem();
        jmiObrisiAutomobil = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jrbRegistracija = new javax.swing.JRadioButton();
        jrbJmbgVlasnika = new javax.swing.JRadioButton();
        jtfPretraga = new javax.swing.JTextField();
        jbtObrisi = new javax.swing.JButton();
        jbtPronadji = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPromenaAutomobila = new javax.swing.JTable();
        jlObavestenja = new javax.swing.JLabel();
        jbtPonisti = new javax.swing.JButton();
        jbtPrikaziSveAutomobile = new javax.swing.JButton();

        jmiDetaljiAutomobila.setText("jMenuItem1");
        jmiDetaljiAutomobila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDetaljiAutomobilaActionPerformed(evt);
            }
        });
        jpmObrisiAutomobil.add(jmiDetaljiAutomobila);

        jmiObrisiAutomobil.setText("jMenuItem1");
        jmiObrisiAutomobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiObrisiAutomobilActionPerformed(evt);
            }
        });
        jpmObrisiAutomobil.add(jmiObrisiAutomobil);

        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true), "Brisanje automobila", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Brisanje podataka o automobilima:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 1, true), "Kriterijum pretrage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 204, 0))); // NOI18N

        buttonGroup1.add(jrbRegistracija);
        jrbRegistracija.setSelected(true);
        jrbRegistracija.setText("Registarski broj automobila");
        jrbRegistracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbRegistracijaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbJmbgVlasnika);
        jrbJmbgVlasnika.setText("JMBG vlasnika");
        jrbJmbgVlasnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbJmbgVlasnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbRegistracija)
                    .addComponent(jrbJmbgVlasnika))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbRegistracija)
                .addGap(18, 18, 18)
                .addComponent(jrbJmbgVlasnika)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jtfPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPretragaKeyReleased(evt);
            }
        });

        jbtObrisi.setText("Obriši");
        jbtObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtObrisiActionPerformed(evt);
            }
        });

        jbtPronadji.setText("Pronađi");
        jbtPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPronadjiActionPerformed(evt);
            }
        });

        jtblPromenaAutomobila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sifra automobila", "Broj registracije", "Marka automobila", "Model automobila", "Vlasnik automobila"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblPromenaAutomobila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtblPromenaAutomobilaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtblPromenaAutomobila);

        jbtPonisti.setText("Poništi");
        jbtPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPonistiActionPerformed(evt);
            }
        });

        jbtPrikaziSveAutomobile.setText("Prikaži sve");
        jbtPrikaziSveAutomobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPrikaziSveAutomobileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlObavestenja, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                    .addComponent(jtfPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jbtPonisti, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtObrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbtPronadji, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(jbtPrikaziSveAutomobile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(93, 93, 93))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtPronadji))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jlObavestenja, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbtPrikaziSveAutomobile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtObrisi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtPonisti)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPronadjiActionPerformed
        BrisanjeAutomobilaKI.vratiObjekat().jbtPronadjiActionPerformed();
    }//GEN-LAST:event_jbtPronadjiActionPerformed

    private void jrbRegistracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRegistracijaActionPerformed
        BrisanjeAutomobilaKI.vratiObjekat().jrbRegistracijaActionPerformed();
    }//GEN-LAST:event_jrbRegistracijaActionPerformed

    private void jtfPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPretragaKeyReleased
        BrisanjeAutomobilaKI.vratiObjekat().jtfPretragaKeyReleased(evt);
    }//GEN-LAST:event_jtfPretragaKeyReleased

    private void jrbJmbgVlasnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbJmbgVlasnikaActionPerformed
        BrisanjeAutomobilaKI.vratiObjekat().jrbJmbgVlasnikaActionPerformed();
    }//GEN-LAST:event_jrbJmbgVlasnikaActionPerformed

    private void jbtObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtObrisiActionPerformed
        BrisanjeAutomobilaKI.vratiObjekat().jbtObrisiActionPerformed();
    }//GEN-LAST:event_jbtObrisiActionPerformed

    private void jtblPromenaAutomobilaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblPromenaAutomobilaMouseReleased
        BrisanjeAutomobilaKI.vratiObjekat().jtblPromenaAutomobilaMouseReleased(evt);
    }//GEN-LAST:event_jtblPromenaAutomobilaMouseReleased

    private void jmiDetaljiAutomobilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDetaljiAutomobilaActionPerformed
        BrisanjeAutomobilaKI.vratiObjekat().jmiDetaljiAutomobilaActionPerformed();
    }//GEN-LAST:event_jmiDetaljiAutomobilaActionPerformed

    private void jmiObrisiAutomobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiObrisiAutomobilActionPerformed
        BrisanjeAutomobilaKI.vratiObjekat().jmiObrisiAutomobilActionPerformed();
    }//GEN-LAST:event_jmiObrisiAutomobilActionPerformed

    private void jbtPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPonistiActionPerformed
        BrisanjeAutomobilaKI.vratiObjekat().jbtPonistiActionPerformed();
    }//GEN-LAST:event_jbtPonistiActionPerformed

    private void jbtPrikaziSveAutomobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPrikaziSveAutomobileActionPerformed
        BrisanjeAutomobilaKI.vratiObjekat().jbtPrikaziSveAutomobileActionPerformed();
    }//GEN-LAST:event_jbtPrikaziSveAutomobileActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtObrisi;
    private javax.swing.JButton jbtPonisti;
    private javax.swing.JButton jbtPrikaziSveAutomobile;
    private javax.swing.JButton jbtPronadji;
    private javax.swing.JLabel jlObavestenja;
    private javax.swing.JMenuItem jmiDetaljiAutomobila;
    private javax.swing.JMenuItem jmiObrisiAutomobil;
    private javax.swing.JPopupMenu jpmObrisiAutomobil;
    private javax.swing.JRadioButton jrbJmbgVlasnika;
    private javax.swing.JRadioButton jrbRegistracija;
    private javax.swing.JTable jtblPromenaAutomobila;
    private javax.swing.JTextField jtfPretraga;
    // End of variables declaration//GEN-END:variables
}
