/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrikazAutomobilaPanel.java
 *
 * Created on Apr 26, 2012, 1:05:27 AM
 */
package paneli.automobili;

import kontrolerKI.automobili.PrikazAutomobilaKI;

/**
 *
 * @author Rus
 */
public class PrikazAutomobilaPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrikazAutomobilaPanel
     */
    public PrikazAutomobilaPanel() {
        initComponents();
        PrikazAutomobilaKI.vratiObjekat().postaviSveKomponente(this, jmiPrikazAutomobila, jpmPrikazAutomobila, jtblPrikazAutomobila);
        PrikazAutomobilaKI.vratiObjekat().prikaziSveAutomobile();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmPrikazAutomobila = new javax.swing.JPopupMenu();
        jmiPrikazAutomobila = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblPrikazAutomobila = new javax.swing.JTable();

        jmiPrikazAutomobila.setText("jMenuItem1");
        jpmPrikazAutomobila.add(jmiPrikazAutomobila);

        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true), "Prikaz podataka o automobilima", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 255)));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36));
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Prikaz podataka o automobilima:");

        jtblPrikazAutomobila.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblPrikazAutomobila);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmiPrikazAutomobila;
    private javax.swing.JPopupMenu jpmPrikazAutomobila;
    private javax.swing.JTable jtblPrikazAutomobila;
    // End of variables declaration//GEN-END:variables
}
