/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PromenaAutomobilaPanel.java
 *
 * Created on Apr 26, 2012, 1:05:37 AM
 */
package paneli.automobili;

import kontrolerKI.automobili.PromenaAutomobilaKI;

/**
 *
 * @author Rus
 */
public class PromenaAutomobilaPanel extends javax.swing.JPanel {

    /**
     * Creates new form PromenaAutomobilaPanel
     */
    public PromenaAutomobilaPanel() {
        initComponents();
        PromenaAutomobilaKI.vratiObjekat().postaviSveKomponente(jPanel1, jcbMarka, jcbModel, jlIme, jlJmbg, jlObavestenja, jlPrezime, jlRegistracija, jmiPromeniPodatke, jpmPromeniPodatke, jrbJmbgVlasnika, jrbRegistracija, jtfImeVlasnika, jtfJmbgVlasnika, jtfPretraga, jtfPrezimeVlasnika, jtfRegistracija, jtfSifraAutomobila, jbtPrethodni, jbtPromeniPodatke, jbtPronadji, jbtSledeci, jbtPonisti);
        PromenaAutomobilaKI.vratiObjekat().srediFormu(false);
        jbtPrethodni.setEnabled(false);
        jbtSledeci.setEnabled(false);
        PromenaAutomobilaKI.vratiObjekat().napuniCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpmPromeniPodatke = new javax.swing.JPopupMenu();
        jmiPromeniPodatke = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jrbRegistracija = new javax.swing.JRadioButton();
        jrbJmbgVlasnika = new javax.swing.JRadioButton();
        jtfPretraga = new javax.swing.JTextField();
        jbtPromeniPodatke = new javax.swing.JButton();
        jbtPronadji = new javax.swing.JButton();
        jbtPonisti = new javax.swing.JButton();
        jlObavestenja = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfSifraAutomobila = new javax.swing.JTextField();
        jtfRegistracija = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcbMarka = new javax.swing.JComboBox();
        jcbModel = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jtfJmbgVlasnika = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtfImeVlasnika = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtfPrezimeVlasnika = new javax.swing.JTextField();
        jlJmbg = new javax.swing.JLabel();
        jlIme = new javax.swing.JLabel();
        jlRegistracija = new javax.swing.JLabel();
        jlPrezime = new javax.swing.JLabel();
        jbtSledeci = new javax.swing.JButton();
        jbtPrethodni = new javax.swing.JButton();

        jmiPromeniPodatke.setText("jMenuItem1");
        jpmPromeniPodatke.add(jmiPromeniPodatke);

        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true), "Promena podataka o automobilima", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 255)));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36));
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Promena podataka o automobilima:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 1, true), "Kriterijum pretrage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 204, 0)));

        buttonGroup1.add(jrbRegistracija);
        jrbRegistracija.setSelected(true);
        jrbRegistracija.setText("Registarski broj automobila");
        jrbRegistracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbRegistracijaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbJmbgVlasnika);
        jrbJmbgVlasnika.setText("JMBG vlasnika");
        jrbJmbgVlasnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbJmbgVlasnikaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbRegistracija)
                    .addComponent(jrbJmbgVlasnika))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbRegistracija)
                .addGap(18, 18, 18)
                .addComponent(jrbJmbgVlasnika)
                .addGap(8, 8, 8))
        );

        jtfPretraga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfPretragaFocusGained(evt);
            }
        });
        jtfPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPretragaKeyReleased(evt);
            }
        });

        jbtPromeniPodatke.setText("Promeni podatke");
        jbtPromeniPodatke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPromeniPodatkeActionPerformed(evt);
            }
        });

        jbtPronadji.setText("Pronađi");
        jbtPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPronadjiActionPerformed(evt);
            }
        });

        jbtPonisti.setText("Poništi");
        jbtPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPonistiActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 1, true), "Podaci o automobilu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 204, 0)));

        jLabel2.setText("Šifra automobila:");

        jLabel3.setText("Broj registracije:");

        jLabel4.setText("Marka:");

        jLabel5.setText("Model:");

        jcbMarka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMarkaActionPerformed(evt);
            }
        });

        jLabel6.setText("JMBG vlasnika:");

        jLabel7.setText("Ime vlasnika:");

        jLabel8.setText("Prezime vlasnika:");

        jbtSledeci.setText(">>");
        jbtSledeci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSledeciActionPerformed(evt);
            }
        });

        jbtPrethodni.setText("<<");
        jbtPrethodni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPrethodniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jbtPrethodni)
                .addGap(18, 18, 18)
                .addComponent(jbtSledeci)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtfImeVlasnika, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jtfJmbgVlasnika, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jcbMarka, javax.swing.GroupLayout.Alignment.LEADING, 0, 256, Short.MAX_VALUE)
                            .addComponent(jtfRegistracija, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jtfSifraAutomobila, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(jcbModel, javax.swing.GroupLayout.Alignment.LEADING, 0, 256, Short.MAX_VALUE)
                            .addComponent(jtfPrezimeVlasnika, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlIme, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jlPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfSifraAutomobila, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jlRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtfRegistracija, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcbMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jcbModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtfJmbgVlasnika, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jtfImeVlasnika, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlIme, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jtfPrezimeVlasnika, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtSledeci)
                        .addComponent(jbtPrethodni))
                    .addComponent(jlPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlObavestenja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(jbtPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jbtPromeniPodatke, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addGap(66, 66, 66)
                .addComponent(jbtPonisti, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtPronadji))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlObavestenja, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtPonisti)
                    .addComponent(jbtPromeniPodatke))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrbRegistracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRegistracijaActionPerformed
        PromenaAutomobilaKI.vratiObjekat().jrbRegistracija();

    }//GEN-LAST:event_jrbRegistracijaActionPerformed

    private void jtfPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPretragaKeyReleased
        PromenaAutomobilaKI.vratiObjekat().jtfPretragaKeyReleased(evt);
    }//GEN-LAST:event_jtfPretragaKeyReleased

    private void jbtPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPronadjiActionPerformed
        PromenaAutomobilaKI.vratiObjekat().jbtPronadji();
    }//GEN-LAST:event_jbtPronadjiActionPerformed

    private void jbtPromeniPodatkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPromeniPodatkeActionPerformed
        PromenaAutomobilaKI.vratiObjekat().jbtPromeniPodatkeActionPerformed();
    }//GEN-LAST:event_jbtPromeniPodatkeActionPerformed

    private void jbtPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPonistiActionPerformed
        PromenaAutomobilaKI.vratiObjekat().jbtPonisti();

    }//GEN-LAST:event_jbtPonistiActionPerformed

    private void jrbJmbgVlasnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbJmbgVlasnikaActionPerformed
        PromenaAutomobilaKI.vratiObjekat().jrbJmbgVlasnikaActionPerformed();

    }//GEN-LAST:event_jrbJmbgVlasnikaActionPerformed

    private void jtfPretragaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfPretragaFocusGained
        PromenaAutomobilaKI.vratiObjekat().jtfPretragaFocusGained();

    }//GEN-LAST:event_jtfPretragaFocusGained

    private void jcbMarkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMarkaActionPerformed
        PromenaAutomobilaKI.vratiObjekat().jcbMarkaActionPerformed();
    }//GEN-LAST:event_jcbMarkaActionPerformed

    private void jbtSledeciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSledeciActionPerformed
        PromenaAutomobilaKI.vratiObjekat().jbtSledeciActionPerformed();
    }//GEN-LAST:event_jbtSledeciActionPerformed

    private void jbtPrethodniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPrethodniActionPerformed
        PromenaAutomobilaKI.vratiObjekat().jbtPrethodniActionPerformed();
    }//GEN-LAST:event_jbtPrethodniActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtPonisti;
    private javax.swing.JButton jbtPrethodni;
    private javax.swing.JButton jbtPromeniPodatke;
    private javax.swing.JButton jbtPronadji;
    private javax.swing.JButton jbtSledeci;
    private javax.swing.JComboBox jcbMarka;
    private javax.swing.JComboBox jcbModel;
    private javax.swing.JLabel jlIme;
    private javax.swing.JLabel jlJmbg;
    private javax.swing.JLabel jlObavestenja;
    private javax.swing.JLabel jlPrezime;
    private javax.swing.JLabel jlRegistracija;
    private javax.swing.JMenuItem jmiPromeniPodatke;
    private javax.swing.JPopupMenu jpmPromeniPodatke;
    private javax.swing.JRadioButton jrbJmbgVlasnika;
    private javax.swing.JRadioButton jrbRegistracija;
    private javax.swing.JTextField jtfImeVlasnika;
    private javax.swing.JTextField jtfJmbgVlasnika;
    private javax.swing.JTextField jtfPretraga;
    private javax.swing.JTextField jtfPrezimeVlasnika;
    private javax.swing.JTextField jtfRegistracija;
    private javax.swing.JTextField jtfSifraAutomobila;
    // End of variables declaration//GEN-END:variables
}
