    // Variables declaration - do not modify
// End of variables declaration
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UnosAutomobilaPanel.java
 *
 * Created on Apr 26, 2012, 1:05:16 AM
 */
package paneli.automobili;

import kontrolerKI.automobili.UnosAutomobilaKI;

/**
 *
 * @author Rus
 */
public class UnosAutomobilaPanel extends javax.swing.JPanel {

    /**
     * Creates new form UnosAutomobilaPanel
     */
    public UnosAutomobilaPanel() {
        initComponents();
        UnosAutomobilaKI.vratiObjekat().postaviSveKomponente(jPanel1, jcbMarkaAutomobila, jcbModelAutomobila, jcbVlasnik, jlBrojRegistracije, jlIme, jlJmbg, jlLogo, jlPrezime, jlSifraAutomobila, jplNoviKlijent, jtfBrojRegistracije, jtfImeKlijenta, jtfJmbgKlijenta, jtfPrezimeKlijenta, jtfSifraAutomobila);
        UnosAutomobilaKI.vratiObjekat().srediFormu();
        UnosAutomobilaKI.vratiObjekat().comboKorisnici();
        UnosAutomobilaKI.vratiObjekat().comboMarke();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfSifraAutomobila = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcbMarkaAutomobila = new javax.swing.JComboBox();
        jcbModelAutomobila = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jbtUbaciPodatke = new javax.swing.JButton();
        jtfBrojRegistracije = new javax.swing.JTextField();
        jlSifraAutomobila = new javax.swing.JLabel();
        jlBrojRegistracije = new javax.swing.JLabel();
        jcbVlasnik = new javax.swing.JComboBox();
        jbtDodajNovogKlijenta = new javax.swing.JButton();
        jplNoviKlijent = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtfJmbgKlijenta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtfImeKlijenta = new javax.swing.JTextField();
        jtfPrezimeKlijenta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jbtDodaj = new javax.swing.JButton();
        jlJmbg = new javax.swing.JLabel();
        jlIme = new javax.swing.JLabel();
        jlPrezime = new javax.swing.JLabel();
        jlLogo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true), "Unos automobila", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 255)));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36));
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Unos podataka o automobilima:");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Šifra automobila:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));
        jPanel1.add(jtfSifraAutomobila, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 297, 25));

        jLabel3.setText("Broj registracije:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel4.setText("Automobil:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel5.setText("Vlasnik:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        jLabel7.setText("Marka:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        jcbMarkaAutomobila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMarkaAutomobilaActionPerformed(evt);
            }
        });
        jcbMarkaAutomobila.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcbMarkaAutomobilaKeyReleased(evt);
            }
        });
        jPanel1.add(jcbMarkaAutomobila, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 210, 25));

        jcbModelAutomobila.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcbModelAutomobilaKeyReleased(evt);
            }
        });
        jPanel1.add(jcbModelAutomobila, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 209, 25));

        jLabel8.setText("Model:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jbtUbaciPodatke.setText("Ubaci podatke");
        jbtUbaciPodatke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUbaciPodatkeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtUbaciPodatke, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 118, -1));

        jtfBrojRegistracije.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBrojRegistracijeKeyReleased(evt);
            }
        });
        jPanel1.add(jtfBrojRegistracije, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 297, 25));
        jPanel1.add(jlSifraAutomobila, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 179, 22));
        jPanel1.add(jlBrojRegistracije, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 179, 22));

        jcbVlasnik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcbVlasnikKeyReleased(evt);
            }
        });
        jPanel1.add(jcbVlasnik, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 300, 25));

        jbtDodajNovogKlijenta.setText("Dodaj novog klijenta");
        jbtDodajNovogKlijenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDodajNovogKlijentaActionPerformed(evt);
            }
        });
        jbtDodajNovogKlijenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jbtDodajNovogKlijentaKeyReleased(evt);
            }
        });
        jPanel1.add(jbtDodajNovogKlijenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 150, -1));

        jplNoviKlijent.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 1, true), "Novi klijent", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 204, 0)));

        jLabel6.setText("JMBG:");

        jtfJmbgKlijenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfJmbgKlijentaKeyReleased(evt);
            }
        });

        jLabel9.setText("Ime:");

        jtfImeKlijenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfImeKlijentaKeyReleased(evt);
            }
        });

        jtfPrezimeKlijenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPrezimeKlijentaKeyReleased(evt);
            }
        });

        jLabel10.setText("Prezime:");

        jbtDodaj.setText("Dodaj");
        jbtDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDodajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplNoviKlijentLayout = new javax.swing.GroupLayout(jplNoviKlijent);
        jplNoviKlijent.setLayout(jplNoviKlijentLayout);
        jplNoviKlijentLayout.setHorizontalGroup(
            jplNoviKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplNoviKlijentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplNoviKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplNoviKlijentLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(jtfImeKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplNoviKlijentLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jtfJmbgKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplNoviKlijentLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jlJmbg, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplNoviKlijentLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jlIme, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplNoviKlijentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jtfPrezimeKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplNoviKlijentLayout.createSequentialGroup()
                .addContainerGap(159, Short.MAX_VALUE)
                .addComponent(jbtDodaj)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplNoviKlijentLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jlPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        jplNoviKlijentLayout.setVerticalGroup(
            jplNoviKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplNoviKlijentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplNoviKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfJmbgKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jplNoviKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfImeKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlIme, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jplNoviKlijentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfPrezimeKlijenta, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jbtDodaj)
                .addContainerGap())
        );

        jPanel1.add(jplNoviKlijent, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 320, 260));
        jPanel1.add(jlLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 70, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtDodajNovogKlijentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDodajNovogKlijentaActionPerformed

        UnosAutomobilaKI.vratiObjekat().dodajNovogKlijenta();

    }//GEN-LAST:event_jbtDodajNovogKlijentaActionPerformed

    private void jtfBrojRegistracijeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBrojRegistracijeKeyReleased

        UnosAutomobilaKI.vratiObjekat().brojRegistracijeKeyRelease(evt);

    }//GEN-LAST:event_jtfBrojRegistracijeKeyReleased

    private void jcbMarkaAutomobilaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbMarkaAutomobilaKeyReleased
        UnosAutomobilaKI.vratiObjekat().jcbMarkaAutomobilaKeyReleased(evt);
    }//GEN-LAST:event_jcbMarkaAutomobilaKeyReleased

    private void jcbModelAutomobilaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbModelAutomobilaKeyReleased
        UnosAutomobilaKI.vratiObjekat().jcbModelAutomobilaKeyReleased(evt);

    }//GEN-LAST:event_jcbModelAutomobilaKeyReleased

    private void jcbVlasnikKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcbVlasnikKeyReleased
        UnosAutomobilaKI.vratiObjekat().jcbVlasnikKeyReleased(evt);
        
    }//GEN-LAST:event_jcbVlasnikKeyReleased

    private void jbtDodajNovogKlijentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtDodajNovogKlijentaKeyReleased
        UnosAutomobilaKI.vratiObjekat().jbtDodajNovogKlijentaKeyReleased(evt);

    }//GEN-LAST:event_jbtDodajNovogKlijentaKeyReleased

    private void jtfJmbgKlijentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfJmbgKlijentaKeyReleased
        UnosAutomobilaKI.vratiObjekat().jtfJmbgKlijentaKeyReleased(evt);

    }//GEN-LAST:event_jtfJmbgKlijentaKeyReleased

    private void jtfImeKlijentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfImeKlijentaKeyReleased
        UnosAutomobilaKI.vratiObjekat().jtfImeKlijentaKeyReleased(evt);

    }//GEN-LAST:event_jtfImeKlijentaKeyReleased

    private void jtfPrezimeKlijentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPrezimeKlijentaKeyReleased
        UnosAutomobilaKI.vratiObjekat().jtfPrezimeKlijentaKeyReleased(evt);
        
    }//GEN-LAST:event_jtfPrezimeKlijentaKeyReleased

    private void jbtDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDodajActionPerformed
        UnosAutomobilaKI.vratiObjekat().dodaj();
    }//GEN-LAST:event_jbtDodajActionPerformed

    private void jcbMarkaAutomobilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMarkaAutomobilaActionPerformed
        UnosAutomobilaKI.vratiObjekat().markaAutomobila();
    }//GEN-LAST:event_jcbMarkaAutomobilaActionPerformed

    private void jbtUbaciPodatkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUbaciPodatkeActionPerformed
        UnosAutomobilaKI.vratiObjekat().ubaciPodatke();
    }//GEN-LAST:event_jbtUbaciPodatkeActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtDodaj;
    private javax.swing.JButton jbtDodajNovogKlijenta;
    private javax.swing.JButton jbtUbaciPodatke;
    private javax.swing.JComboBox jcbMarkaAutomobila;
    private javax.swing.JComboBox jcbModelAutomobila;
    private javax.swing.JComboBox jcbVlasnik;
    private javax.swing.JLabel jlBrojRegistracije;
    private javax.swing.JLabel jlIme;
    private javax.swing.JLabel jlJmbg;
    private javax.swing.JLabel jlLogo;
    private javax.swing.JLabel jlPrezime;
    private javax.swing.JLabel jlSifraAutomobila;
    private javax.swing.JPanel jplNoviKlijent;
    private javax.swing.JTextField jtfBrojRegistracije;
    private javax.swing.JTextField jtfImeKlijenta;
    private javax.swing.JTextField jtfJmbgKlijenta;
    private javax.swing.JTextField jtfPrezimeKlijenta;
    private javax.swing.JTextField jtfSifraAutomobila;
    // End of variables declaration//GEN-END:variables
}
