/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PromenaIntervencijePanel.java
 *
 * Created on Apr 26, 2012, 1:04:12 AM
 */
package paneli.intervencije;

import domen.Automobil;
import domen.Intervencija;
import domen.OpisIntervencije;
import domen.VlasnikAutomobila;
import domen.Zaposleni;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import komunikacija.Komunikacija;
import kontrolerKI.automobili.PromenaAutomobilaKI;
import kontrolerKI.intervencije.PromenaIntervencijeKI;
import ogranicenja.JTextFieldOgranicenje;
import transfer.TransferKlasa;
import util.Konstante;
import validator.ComponentValidator;
import validator.PraznoPoljeValidator;

/**
 *
 * @author Rus
 */
public class PromenaIntervencijePanel extends javax.swing.JPanel {

    /**
     * Creates new form PromenaIntervencijePanel
     */
    public PromenaIntervencijePanel() {
        initComponents();
        PromenaIntervencijeKI.vratiObjekat().postaviSveKomponente(this, jbtPonisti, jbtPromeniPodatke, jbtPronadji, jcbAutomobil, jcbRadniciPretraga, jcbRadnik, jftfDatumIntervencije, jlIme, jlJmbg, jlObavestenje, jlPrezime, jmiPromeniPodatke, jpmPromeniPodatke, jrbRadnik, jrbRegistracija, jtfImeVlasnika, jtfJmbgVlasnika, jtfPretraga, jtfPrezimeVlasnika, jtfSifraIntervencije);
        PromenaIntervencijeKI.vratiObjekat().srediFormu(false);
        PromenaIntervencijeKI.vratiObjekat().napuniCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jpmPromeniPodatke = new javax.swing.JPopupMenu();
        jmiPromeniPodatke = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jrbRegistracija = new javax.swing.JRadioButton();
        jrbRadnik = new javax.swing.JRadioButton();
        jtfPretraga = new javax.swing.JTextField();
        jbtPronadji = new javax.swing.JButton();
        jbtPromeniPodatke = new javax.swing.JButton();
        jlObavestenje = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfSifraIntervencije = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbRadnik = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jcbAutomobil = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jtfJmbgVlasnika = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfImeVlasnika = new javax.swing.JTextField();
        jtfPrezimeVlasnika = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jlJmbg = new javax.swing.JLabel();
        jlIme = new javax.swing.JLabel();
        jlPrezime = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jftfDatumIntervencije = new javax.swing.JFormattedTextField();
        jbtPonisti = new javax.swing.JButton();
        jcbRadniciPretraga = new javax.swing.JComboBox();

        jmiPromeniPodatke.setText("jMenuItem1");
        jpmPromeniPodatke.add(jmiPromeniPodatke);

        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true), "Promena podataka intervencije", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 0, 255)));

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36));
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Promena podataka o intervencijama:");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 1, true), "Pretraga intervencija", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 204, 0)));

        buttonGroup1.add(jrbRegistracija);
        jrbRegistracija.setSelected(true);
        jrbRegistracija.setText("Registarski broj automobila");
        jrbRegistracija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbRegistracijaActionPerformed(evt);
            }
        });

        buttonGroup1.add(jrbRadnik);
        jrbRadnik.setText("Radnik");
        jrbRadnik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbRadnikActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbRegistracija)
                    .addComponent(jrbRadnik))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbRegistracija)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbRadnik)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtfPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfPretragaKeyReleased(evt);
            }
        });

        jbtPronadji.setText("Pronađi");
        jbtPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPronadjiActionPerformed(evt);
            }
        });

        jbtPromeniPodatke.setText("Promeni podatke");
        jbtPromeniPodatke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPromeniPodatkeActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 204, 0), 1, true), "Podaci o intervenciji", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 204, 0)));

        jLabel2.setText("Šifra intervencije:");

        jLabel3.setText("Radnik:");

        jLabel4.setText("Automobil:");

        jLabel5.setText("JMBG vlasnika:");

        jLabel6.setText("Ime vlasnika:");

        jLabel7.setText("Prezime vlasnika:");

        jLabel8.setText("Datum intervencije:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jftfDatumIntervencije, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jtfSifraIntervencije, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jtfImeVlasnika, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jtfJmbgVlasnika, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jtfPrezimeVlasnika, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(jcbRadnik, 0, 218, Short.MAX_VALUE)
                    .addComponent(jcbAutomobil, 0, 218, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlIme, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jlPrezime, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addGap(133, 133, 133))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfSifraIntervencije, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbRadnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcbAutomobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jtfJmbgVlasnika, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfImeVlasnika, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addComponent(jlIme, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtfPrezimeVlasnika, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jftfDatumIntervencije, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jbtPonisti.setText("Poništi");
        jbtPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPonistiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(69, 69, 69)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jcbRadniciPretraga, 0, 247, Short.MAX_VALUE)
                                .addComponent(jtfPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(102, 102, 102)
                                    .addComponent(jbtPronadji, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jlObavestenje, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(258, 258, 258)
                            .addComponent(jbtPromeniPodatke)
                            .addGap(63, 63, 63)
                            .addComponent(jbtPonisti, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtPronadji)
                            .addComponent(jtfPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcbRadniciPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlObavestenje, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtPromeniPodatke)
                    .addComponent(jbtPonisti))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtfPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPretragaKeyReleased
        PromenaIntervencijeKI.vratiObjekat().jtfPretragaKeyReleased(evt);
    }//GEN-LAST:event_jtfPretragaKeyReleased

    private void jbtPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPronadjiActionPerformed
        PromenaIntervencijeKI.vratiObjekat().jbtPronadjiActionPerformed();
    }//GEN-LAST:event_jbtPronadjiActionPerformed

    private void jrbRegistracijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRegistracijaActionPerformed
        PromenaIntervencijeKI.vratiObjekat().jrbRegistracijaActionPerformed();
    }//GEN-LAST:event_jrbRegistracijaActionPerformed

    private void jrbRadnikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbRadnikActionPerformed
        PromenaIntervencijeKI.vratiObjekat().jrbRadnikActionPerformed();
    }//GEN-LAST:event_jrbRadnikActionPerformed

    private void jbtPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPonistiActionPerformed
        PromenaIntervencijeKI.vratiObjekat().jbtPonistiActionPerformed();
    }//GEN-LAST:event_jbtPonistiActionPerformed

    private void jbtPromeniPodatkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPromeniPodatkeActionPerformed
        PromenaIntervencijeKI.vratiObjekat().jbtPromeniPodatkeActionPerformed();
    }//GEN-LAST:event_jbtPromeniPodatkeActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtPonisti;
    private javax.swing.JButton jbtPromeniPodatke;
    private javax.swing.JButton jbtPronadji;
    private javax.swing.JComboBox jcbAutomobil;
    private javax.swing.JComboBox jcbRadniciPretraga;
    private javax.swing.JComboBox jcbRadnik;
    private javax.swing.JFormattedTextField jftfDatumIntervencije;
    private javax.swing.JLabel jlIme;
    private javax.swing.JLabel jlJmbg;
    private javax.swing.JLabel jlObavestenje;
    private javax.swing.JLabel jlPrezime;
    private javax.swing.JMenuItem jmiPromeniPodatke;
    private javax.swing.JPopupMenu jpmPromeniPodatke;
    private javax.swing.JRadioButton jrbRadnik;
    private javax.swing.JRadioButton jrbRegistracija;
    private javax.swing.JTextField jtfImeVlasnika;
    private javax.swing.JTextField jtfJmbgVlasnika;
    private javax.swing.JTextField jtfPretraga;
    private javax.swing.JTextField jtfPrezimeVlasnika;
    private javax.swing.JTextField jtfSifraIntervencije;
    // End of variables declaration//GEN-END:variables
}
