/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlacanjeDugovanjaPanel.java
 *
 * Created on Apr 26, 2012, 1:06:42 AM
 */
package paneli.dugovanja;

import kontrolerKI.dugovanja.PlacanjeDugovanjaKI;

/**
 *
 * @author Rus
 */
public class PlacanjeDugovanjaPanel extends javax.swing.JPanel {

    /**
     * Creates new form PlacanjeDugovanjaPanel
     */
    public PlacanjeDugovanjaPanel() {
        initComponents();
        PlacanjeDugovanjaKI.vratiObjekat().postaviSveKomponente(this, jlObavestenje, jmiDetalji, jmiNaplataDugovanja, jmiNaplataDugovanjaNekogKorisnika, jpmDugovanja, jtblDugovanja, jtfPretraga, jtfUkupanDug);
        PlacanjeDugovanjaKI.vratiObjekat().srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmDugovanja = new javax.swing.JPopupMenu();
        jmiDetalji = new javax.swing.JMenuItem();
        jmiNaplataDugovanja = new javax.swing.JMenuItem();
        jmiNaplataDugovanjaNekogKorisnika = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfPretraga = new javax.swing.JTextField();
        jbtPronadji = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDugovanja = new javax.swing.JTable();
        jbtNaplataDuga = new javax.swing.JButton();
        jbtNaplataSvihDugovanja = new javax.swing.JButton();
        jbtPrikaziSvaDugovanja = new javax.swing.JButton();
        jbtPonisti = new javax.swing.JButton();
        jlObavestenje = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfUkupanDug = new javax.swing.JTextField();

        jmiDetalji.setText("jMenuItem1");
        jmiDetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDetaljiActionPerformed(evt);
            }
        });
        jpmDugovanja.add(jmiDetalji);

        jmiNaplataDugovanja.setText("jMenuItem1");
        jmiNaplataDugovanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNaplataDugovanjaActionPerformed(evt);
            }
        });
        jpmDugovanja.add(jmiNaplataDugovanja);

        jmiNaplataDugovanjaNekogKorisnika.setText("jMenuItem1");
        jmiNaplataDugovanjaNekogKorisnika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNaplataDugovanjaNekogKorisnikaActionPerformed(evt);
            }
        });
        jpmDugovanja.add(jmiNaplataDugovanjaNekogKorisnika);

        setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 1, true), "Naplata dugovanja", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Naplata dugovanja:");

        jLabel2.setText("JMBG korisnika:");

        jtfPretraga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfPretragaKeyPressed(evt);
            }
        });

        jbtPronadji.setText("Pronađi");
        jbtPronadji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPronadjiActionPerformed(evt);
            }
        });

        jtblDugovanja.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sifra dugovanja", "Vrednost dugovanja", "JMBG vlasnika", "Ime", "Prezime"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblDugovanja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jtblDugovanjaMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jtblDugovanja);

        jbtNaplataDuga.setText("Naplata duga");
        jbtNaplataDuga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNaplataDugaActionPerformed(evt);
            }
        });

        jbtNaplataSvihDugovanja.setText("Naplata svih dugovanja");
        jbtNaplataSvihDugovanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtNaplataSvihDugovanjaActionPerformed(evt);
            }
        });

        jbtPrikaziSvaDugovanja.setText("Prikaži sve dugove");
        jbtPrikaziSvaDugovanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPrikaziSvaDugovanjaActionPerformed(evt);
            }
        });

        jbtPonisti.setText("Poništi");
        jbtPonisti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPonistiActionPerformed(evt);
            }
        });

        jLabel3.setText("Ukupan dug:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfUkupanDug, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPretraga, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jlObavestenje, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtPonisti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtPronadji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtPrikaziSvaDugovanja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(227, 227, 227))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbtNaplataDuga, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(jbtNaplataSvihDugovanja)
                        .addGap(215, 215, 215))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlObavestenje, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jtfPretraga, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jbtPronadji)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtPrikaziSvaDugovanja)
                        .addGap(18, 18, 18)
                        .addComponent(jbtPonisti)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfUkupanDug, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                            .addComponent(jLabel3))
                        .addGap(43, 43, 43)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtNaplataSvihDugovanja)
                    .addComponent(jbtNaplataDuga))
                .addGap(47, 47, 47))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtPrikaziSvaDugovanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPrikaziSvaDugovanjaActionPerformed
        PlacanjeDugovanjaKI.vratiObjekat().jbtPrikaziSvaDugovanjaActionPerformed();
    }//GEN-LAST:event_jbtPrikaziSvaDugovanjaActionPerformed

    private void jbtPonistiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPonistiActionPerformed
        PlacanjeDugovanjaKI.vratiObjekat().jbtPonistiActionPerformed();
    }//GEN-LAST:event_jbtPonistiActionPerformed

    private void jbtPronadjiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPronadjiActionPerformed
        PlacanjeDugovanjaKI.vratiObjekat().jbtPronadjiActionPerformed();
    }//GEN-LAST:event_jbtPronadjiActionPerformed

    private void jtblDugovanjaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblDugovanjaMouseReleased
        PlacanjeDugovanjaKI.vratiObjekat().jtblDugovanjaMouseReleased(evt);
    }//GEN-LAST:event_jtblDugovanjaMouseReleased

    private void jmiDetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDetaljiActionPerformed
        PlacanjeDugovanjaKI.vratiObjekat().jmiDetaljiActionPerformed();
    }//GEN-LAST:event_jmiDetaljiActionPerformed

    private void jbtNaplataDugaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNaplataDugaActionPerformed
        PlacanjeDugovanjaKI.vratiObjekat().jbtNaplataDugaActionPerformed();
    }//GEN-LAST:event_jbtNaplataDugaActionPerformed

    private void jbtNaplataSvihDugovanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtNaplataSvihDugovanjaActionPerformed
        PlacanjeDugovanjaKI.vratiObjekat().jbtNaplataSvihDugovanjaActionPerformed();
    }//GEN-LAST:event_jbtNaplataSvihDugovanjaActionPerformed

    private void jmiNaplataDugovanjaNekogKorisnikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNaplataDugovanjaNekogKorisnikaActionPerformed
        PlacanjeDugovanjaKI.vratiObjekat().jmiNaplataDugovanjaNekogKorisnikaActionPerformed();
    }//GEN-LAST:event_jmiNaplataDugovanjaNekogKorisnikaActionPerformed

    private void jmiNaplataDugovanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNaplataDugovanjaActionPerformed
        PlacanjeDugovanjaKI.vratiObjekat().jmiNaplataDugovanjaActionPerformed();
    }//GEN-LAST:event_jmiNaplataDugovanjaActionPerformed

    private void jtfPretragaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfPretragaKeyPressed
        PlacanjeDugovanjaKI.vratiObjekat().jtfPretragaKeyPressed(evt);
    }//GEN-LAST:event_jtfPretragaKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtNaplataDuga;
    private javax.swing.JButton jbtNaplataSvihDugovanja;
    private javax.swing.JButton jbtPonisti;
    private javax.swing.JButton jbtPrikaziSvaDugovanja;
    private javax.swing.JButton jbtPronadji;
    private javax.swing.JLabel jlObavestenje;
    private javax.swing.JMenuItem jmiDetalji;
    private javax.swing.JMenuItem jmiNaplataDugovanja;
    private javax.swing.JMenuItem jmiNaplataDugovanjaNekogKorisnika;
    private javax.swing.JPopupMenu jpmDugovanja;
    private javax.swing.JTable jtblDugovanja;
    private javax.swing.JTextField jtfPretraga;
    private javax.swing.JTextField jtfUkupanDug;
    // End of variables declaration//GEN-END:variables
}
